%global corefreq_version 2.0.8

Name:           corefreq
Version:        %{corefreq_version}
Release:        3%{?dist}
Summary:        CPU monitoring software with DKMS kernel module

License:        GPL-2.0-only
URL:            https://github.com/cyring/CoreFreq
# Corrected Source0 URL with on-the-fly renaming
Source0:        %{url}/archive/refs/tags/%{version}.tar.gz#/%{name}-%{version}.tar.gz
Source1:        corefreqd.service
Source2:        dkms.conf

BuildRequires:  gcc make kernel-devel dkms kmod systemd-rpm-macros
BuildRequires:  openssl mokutil
Requires:       dkms kernel-devel openssl mokutil

%description
CoreFreq is a CPU monitoring software designed for 64-bit Processors.
This package provides the user-space tools and the DKMS source for the
'corefreqk' kernel module. It fully automates key generation and signing
for Secure Boot systems.

%prep
%autosetup -n CoreFreq-%{version} -p1
cp %{SOURCE2} .
sed -i 's/@RPM_VERSION@/%{version}/' dkms.conf

%build
make %{?_smp_mflags} corefreqd corefreq-cli

%install
install -D -m 0755 build/corefreqd %{buildroot}%{_bindir}/corefreqd
install -D -m 0755 build/corefreq-cli %{buildroot}%{_bindir}/corefreq-cli
install -D -m 0644 %{SOURCE1} %{buildroot}%{_unitdir}/corefreqd.service
rm -rf build
%global dkms_source_dir %{_usrsrc}/%{name}-%{version}
install -d -m 755 %{buildroot}%{dkms_source_dir}
cp -a . %{buildroot}%{dkms_source_dir}/

%post
# ==============================================================================
# Level 3 Fully Automatic Secure Boot Setup
# ==============================================================================
MOK_KEY_DIR="/etc/pki/corefreq"
MOK_PRIV_KEY="${MOK_KEY_DIR}/private_key.priv"
MOK_PUB_KEY="${MOK_KEY_DIR}/public_key.der"
DKMS_SIGN_CONF="/etc/dkms/sign.conf"

# --- STEP 1: Generate Key if it's the first time ---
if [ ! -f "${MOK_PRIV_KEY}" ]; then
    echo "--- Secure Boot key not found. Generating a new key for CoreFreq ---"
    mkdir -p "${MOK_KEY_DIR}"
    openssl req -new -x509 -newkey rsa:2048 -keyout "${MOK_PRIV_KEY}" -outform DER -out "${MOK_PUB_KEY}" -nodes -days 36500 -subj "/CN=CoreFreq DKMS Signing Key/" >/dev/null 2>&1
    
    echo "----------------------------------------------------------------------"
    echo "ATTENTION: SECURE BOOT ONE-TIME SETUP"
    echo "A new key has been generated to automatically sign kernel modules."
    echo "You must now enroll this key into your system's firmware (UEFI)."
    echo
    echo "To do this, please follow these steps:"
    echo "1. Run this command:"
    echo "   sudo mokutil --import ${MOK_PUB_KEY}"
    echo "   (You will be asked to create a password for this one-time action.)"
    echo
    echo "2. Reboot your computer."
    echo
    echo "3. At the blue 'MOK Manager' screen, select 'Enroll MOK',"
    echo "   'Continue', and enter the password you just created."
    echo "----------------------------------------------------------------------"
fi

# --- STEP 2: Create the system-wide DKMS signing config if it doesn't exist ---
if [ ! -f "${DKMS_SIGN_CONF}" ]; then
    echo "--- DKMS signing configuration not found. Creating it for you. ---"
    cat > "${DKMS_SIGN_CONF}" << EOF
# Configuration for DKMS to automatically sign kernel modules.
# This file was automatically generated by the corefreq package.

# Path to the private key
SIGN_PRIVATE_KEY="${MOK_PRIV_KEY}"

# Path to the public key
SIGN_PUBLIC_KEY="${MOK_PUB_KEY}"

# The command DKMS will run after building a module
POST_BUILD_COMMAND="'/usr/src/kernels/\${kernelver}/scripts/sign-file' sha256 '\${SIGN_PRIVATE_KEY}' '\${SIGN_PUBLIC_KEY}' '\${module_location}/\${module_name}.ko'"
EOF
fi

# --- STEP 3: Standard DKMS install (now with automatic signing hook in place) ---
if dkms status -m %{name} -v %{version} | grep -q installed; then
    dkms remove -m %{name} -v %{version} --all >/dev/null 2>&1 || :
fi
dkms add -m %{name} -v %{version} >/dev/null 2 `%post` script to run.